name: sunday
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  async: ^2.10.0
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  path_provider: ^2.0.12
  provider: ^6.0.5
  redux: ^5.0.0
  redux_epics: ^0.15.1

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true